name: Snake Animation Commit

on:
  schedule:
    - cron: "0 3 * * *" # todos os dias às 03:00 UTC (00h no Brasil)
  workflow_dispatch:

jobs:
  generate-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "Fábio Arruda"
          git config --global user.email "seu-email-aqui@example.com"

      - name: Criar arquivo com data
        run: |
          echo "Atualização automática: $(date)" >> update-log.txt

      - name: Commit e push
        run: |
          git add .
          git commit -m "🟢 Atualização automática: $(date)" || echo "Nada para commitar"
          git push origin main
